### ISSUE TITLE
They stack, but...

### ISSUE THREAD

**Issue by PCThrow** [IchHabeHunger54/PotionBundles#1]
I can create stacks of the bundles, which by the way, is awesome.  Play with that Hot and Cold mod, comes in handy with the drinking mechanic.  Problem is, when I drink from the stack of bundles, it takes from the entire stack, and when exhausted, it only returns the number of bottles and strings as if it was only one item, not the entire stack.

**Comment by IchHabeHunger54** [comment]
oops, my bad. the intention was to not make them stackable. will be in the next update! :D
