### ISSUE TITLE
[1.92.2] Negative uses counter in potion bundles.

### ISSUE THREAD

**Issue by KerberosZwei** [IchHabeHunger54/PotionBundles#13]
By brewing bundles of water bottles in a brewing stand, the bundle changes from 3 uses to 0, and by drinking from it the counter goes negative, effectively having infinite uses and dissapearing the texture of the item.

Tested by trying to brew a bundle of water breathing potions by using 3 bundles of water bottles and following the usual steps to brew the potion normally.

Minecraft v1.19.2
Forge v43.2.14

**Comment by IchHabeHunger54** [comment]
Sorry for only getting back after this time, I forgot this issue existed.

I cannot reproduce this issue, bundles cannot be used in brewing stands to begin with. Please elaborate further.
