### ISSUE TITLE
[1.15.2] Crash on dedicated server due to loading of client class

### ISSUE THREAD

**Issue by theishiopian** [IchHabeHunger54/PotionBundles#4]
It appears this mod is loading a client only class on dedicated servers, causing a crash.

https://pastebin.com/d2cszR1w

**Comment by IchHabeHunger54** [comment]
Please test it without any other mods, in order to see if it is an actual error or "just" an incompatibility.

**Comment by theishiopian** [comment]
Will do

**Comment by IchHabeHunger54** [comment]
Is fixed as of v1.2.1, find it on Curse

**Comment by theishiopian** [comment]
THanks
