### ISSUE TITLE
[Server Crash] Attempted to load class /client/renderer/color/ItemColors for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Cixon** [IchHabeHunger54/PotionBundles#5]
This is a simple fix I imagine.

Using latest PotionBundle Version.
Tested on a forge 1.16.5 v36.1.4 server.

Crashreport:
[crash-2021-04-11_13.54.17-fml.txt](https://github.com/IchHabeHunger54/PotionBundles/files/6292551/crash-2021-04-11_13.54.17-fml.txt)

Logs:
[latest.log](https://github.com/IchHabeHunger54/PotionBundles/files/6292547/latest.log) **Line 234**
[debug.log](https://github.com/IchHabeHunger54/PotionBundles/files/6292549/debug.log)  **Line 2319**

**Comment by IchHabeHunger54** [comment]
Fixed in version 1.3.1, thanks for reporting
