### ISSUE TITLE
[MC 1.16.5] Can't load the game

### ISSUE THREAD

**Issue by TheDarkRisen** [IchHabeHunger54/PotionBundles#6]
After instaling new update I can't load minecraft
Forge: 36.1.0
Mod version: 1.3.1
![image](https://user-images.githubusercontent.com/71900096/114381744-86944700-9b9c-11eb-93a7-649fb9f4e7e3.png)
[crash-2021-04-12_14.32.04-fml.txt](https://github.com/IchHabeHunger54/PotionBundles/files/6295891/crash-2021-04-12_14.32.04-fml.txt)
[latest.log](https://github.com/IchHabeHunger54/PotionBundles/files/6295893/latest.log)

**Comment by IchHabeHunger54** [comment]
Fixed it, thanks for reporting
