### ISSUE TITLE
1.18.2 Crafting potion bundles with more than one string returns the amount of string used initially when bundle is exhausted.

### ISSUE THREAD

**Issue by StormCircuit** [IchHabeHunger54/PotionBundles#9]
For example, craft 2 bundles with a stack of 10 string. When the first stack is exhausted, you will get 10 string back and when the second stack is exhausted you will get the remaining 9 string you used to craft the second bundle.

**Comment by Minecraftschurli** [comment]
Please elaborate what you mean

**Comment by Minecraftschurli** [comment]
Fixed in `1.18.1-1.4` and `1.19-1.5`
